[project]
name = 'reforestation'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.carbon-credits]
path = 'contracts/carbon-credits.clar'
clarity_version = 3
epoch = 3.1

[contracts.reforestation]
path = 'contracts/reforestation.clar'
clarity_version = 3
epoch = 3.1

[contracts.carbon-auctions]
path = 'contracts/carbon-auctions.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
